# 应用服务 WEB 访问端口
server:
  port: 10000
# 应用名称
spring:
  application:
    name: pilipili-tmp
  # THYMELEAF (ThymeleafAutoConfiguration)
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.80.128:8080 #配置Nacos地址
  zipkin:
    base-url: http://192.168.80.128:9411
  sleuth:
    sampler:
      probability: 50

  datasource:
    url: jdbc:mysql://192.168.80.128:3306/pilipili
    username: root
    password: Passw0rd
  servlet:
    multipart:
      max-file-size: 1MB



mybatis:
  mapper-locations: classpath:mapper/*xml
